language: node_js
node_js:
  - 10
  - node

script:
  - 'npm run lint'
  - 'npm test'

before_deploy:
  - npm run travis-deploy $TRAVIS_BRANCH
  - cat "gh-pages/$TRAVIS_BRANCH/coverage/lcov.info" | npx coveralls

jobs:
  include:
    - stage: deployment
      node_js: node
      # For security reasons, deployment variables are set in the settings page of the repository
      deploy:
        - provider: pages
          github_token: $GITHUB_TOKEN
          keep_history: true
          local_dir: gh-pages
          on:
            branch:
              - main
              - develop
        - provider: releases
          api_key: $GITHUB_TOKEN
          draft: true
          on:
            branch: main
            tags: true
        - provider: npm
          email: "giacomo.venturini3@gmail.com"
          api_key: $NPM_TOKEN
          on:
            branch: main
            tags: true